/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Benchmark } from "./types";
export namespace Components {
    interface JhButton {
        "size"?: any;
        "type"?: any | 'primary' | 'secondary';
    }
    interface JhUpdatesForYou {
        "benchmarks": Benchmark[];
        "locale": string;
    }
}
declare global {
    interface HTMLJhButtonElement extends Components.JhButton, HTMLStencilElement {
    }
    var HTMLJhButtonElement: {
        prototype: HTMLJhButtonElement;
        new (): HTMLJhButtonElement;
    };
    interface HTMLJhUpdatesForYouElement extends Components.JhUpdatesForYou, HTMLStencilElement {
    }
    var HTMLJhUpdatesForYouElement: {
        prototype: HTMLJhUpdatesForYouElement;
        new (): HTMLJhUpdatesForYouElement;
    };
    interface HTMLElementTagNameMap {
        "jh-button": HTMLJhButtonElement;
        "jh-updates-for-you": HTMLJhUpdatesForYouElement;
    }
}
declare namespace LocalJSX {
    interface JhButton {
        "size"?: any;
        "type"?: any | 'primary' | 'secondary';
    }
    interface JhUpdatesForYou {
        "benchmarks"?: Benchmark[];
        "locale"?: string;
        "onDetailBtnClick"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "jh-button": JhButton;
        "jh-updates-for-you": JhUpdatesForYou;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jh-button": LocalJSX.JhButton & JSXBase.HTMLAttributes<HTMLJhButtonElement>;
            "jh-updates-for-you": LocalJSX.JhUpdatesForYou & JSXBase.HTMLAttributes<HTMLJhUpdatesForYouElement>;
        }
    }
}
